export const Constant = {
  titleTemperature: "NHIỆT ĐỘ",
  titleDissolveOxy: "ĐỘ O2 HÒA TAN",
  redWarning: "Red warning",
  yellowWarning: "Yellow warning",
  titlepH: "ĐỘ pH",
  titleSalinity: "ĐỘ MẶN",
  temperatureHighHigh: 33,
  temperatureHigh: 30,
  temperatureLow: 20,
  temperatureLowLow: 18,
  dissolveOxyLow: 3.5,
  dissolveOxyLowLow: 5,
  pHHighHigh: 8.5,
  pHHigh: 8,
  pHLow: 7.5,
  pHLowLow: 7,
  salinityHighHigh: 35,
  salinityHigh: 25,
  salinityLow: 10,
  salinityLowLow: 5,

  timeSamplingData: 5000,
};
